# Generated by Django 6.0.1 on 2026-01-10 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(help_text='Szerokość geograficzna (np. 49.179)')),
                ('longitude', models.FloatField(help_text='Długość geograficzna (np. 20.088)')),
                ('altitude', models.IntegerField(help_text='Wysokość n.p.m.')),
                ('radius', models.IntegerField(default=200, help_text='Promień zaliczenia w metrach')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='peaks/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('matched_mountain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mountains.mountain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
