# Generated by Django 6.0.1 on 2026-01-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountain',
            name='altitude',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mountain',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mountain',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mountain',
            name='radius',
            field=models.IntegerField(default=200),
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='badges/')),
                ('mountains', models.ManyToManyField(related_name='badges', to='mountains.mountain')),
            ],
        ),
    ]
